# Generated by Django 5.0.1 on 2024-02-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('dni_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_conexion', models.DateField()),
                ('equipo', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('red', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago_esperada', models.DateField()),
                ('fecha_pago_real', models.DateField(null=True)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.cliente')),
            ],
        ),
    ]
