# Generated by Django 3.2.23 on 2024-01-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('dni_cliente', models.CharField(max_length=50)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_conexion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago_esperada', models.DateField()),
                ('fecha_pago_real', models.DateField(null=True)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(null=True, max_length=50)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionClientes.cliente')),
            ],
        ),
    ]
